- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: "ami-09c813fb71547fc4f"
    sg_id: "sg-09dd70d0e55355d39"
    zone_id: "Z00613851PSQYGT6JZU9Y"
    domain_name: "daws86s.fun"
    instances:
    - mongodb
  tasks:
    - name: create ec2 instances
      amazon.aws.ec2_Instance:
        name: "{{ item }}"
        instance_type: t3.micro
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
      tags: 
         name: "{{ item }}"
         loop: "{{ instances }}"    
         register: ec2_output

    - name: print the ec2 output
      ansible.builtin.debug:
      msg: "{{ ec2_output }}"
